export const AuthoritiesConstant = {

  ROLE_ADMIN: 'ROLE_ADMIN',
  ROLE_USER: 'ROLE_USER',
  HDFS_BROWSER: {
    HDFS_BROWSER_EXECUTE: 'HDFS_BROWSER.HDFS_BROWSER_EXECUTE',
    HDFS_BROWSER_READ: 'HDFS_BROWSER.HDFS_BROWSER_READ',
    HDFS_BROWSER_WRITE: 'HDFS_BROWSER.HDFS_BROWSER_WRITE',
  },
  DATALAKE_DASHBOARD: {
    DATALAKE_DASHBOARD_EXECUTE: 'DATALAKE_DASHBOARD.DATALAKE_DASHBOARD_EXECUTE',
    DATALAKE_DASHBOARD_READ: 'DATALAKE_DASHBOARD.DATALAKE_DASHBOARD_READ',
    DATALAKE_DASHBOARD_WRITE: 'DATALAKE_DASHBOARD.DATALAKE_DASHBOARD_WRITE',
  },
  APPLICATION_MANAGEMENT: {
    APPLICATION_MANAGEMENT_EXECUTE: 'APPLICATION_MANAGEMENT.APPLICATION_MANAGEMENT_EXECUTE',
    APPLICATION_MANAGEMENT_READ: 'APPLICATION_MANAGEMENT.APPLICATION_MANAGEMENT_READ',
    APPLICATION_MANAGEMENT_WRITE: 'APPLICATION_MANAGEMENT.APPLICATION_MANAGEMENT_WRITE',
  },
  PROCESS_MANAGER: {
    PROCESS_MANAGER_EXECUTE: 'PROCESS_MANAGER.PROCESS_MANAGER_EXECUTE',
    PROCESS_MANAGER_READ: 'PROCESS_MANAGER.PROCESS_MANAGER_READ',
    PROCESS_MANAGER_WRITE: 'PROCESS_MANAGER.PROCESS_MANAGER_WRITE',
  },
  INGESTION_MONITOR: {
    INGESTION_MONITOR_EXECUTE: 'INGESTION_MONITOR.INGESTION_MONITOR_EXECUTE',
    INGESTION_MONITOR_READ: 'INGESTION_MONITOR.INGESTION_MONITOR_READ',
    INGESTION_MONITOR_WRITE: 'INGESTION_MONITOR.INGESTION_MONITOR_WRITE'
  },
  INGESTION_FLOW_MANAGER: {
    INGESTION_FLOW_MANAGER_EXECUTE: 'INGESTION_FLOW_MANAGER.INGESTION_FLOW_MANAGER_EXECUTE',
    INGESTION_FLOW_MANAGER_READ: 'INGESTION_FLOW_MANAGER.INGESTION_FLOW_MANAGER_READ',
    INGESTION_FLOW_MANAGER_WRITE: 'INGESTION_FLOW_MANAGER.INGESTION_FLOW_MANAGER_WRITE'
  },
  ROLE_MANAGER: {
    ROLE_MANAGER_EXECUTE: 'ROLE_MANAGER.ROLE_MANAGER_EXECUTE',
    ROLE_MANAGER_READ: 'ROLE_MANAGER.ROLE_MANAGER_READ',
    ROLE_MANAGER_WRITE: 'ROLE_MANAGER.ROLE_MANAGER_WRITE'
  },
  USER_HDFS_MANAGER: {
    USER_HDFS_MANAGER_EXECUTE: 'USER_HDFS_MANAGER.USER_HDFS_MANAGER_EXECUTE',
    USER_HDFS_MANAGER_READ: 'USER_HDFS_MANAGER.USER_HDFS_MANAGER_READ',
    USER_HDFS_MANAGER_WRITE: 'USER_HDFS_MANAGER.USER_HDFS_MANAGER_WRITE'
  },
  USER_MANAGER: {
    USER_MANAGER_EXECUTE: 'USER_MANAGER.USER_MANAGER_EXECUTE',
    USER_MANAGER_READ: 'USER_MANAGER.USER_MANAGER_READ',
    USER_MANAGER_WRITE: 'USER_MANAGER.USER_MANAGER_WRITE'
  },
  CONNECTION_MANAGER: {
    CONNECTION_MANAGER_EXECUTE: 'CONNECTION_MANAGER.CONNECTION_MANAGER_EXECUTE',
    CONNECTION_MANAGER_READ: 'CONNECTION_MANAGER.CONNECTION_MANAGER_READ',
    CONNECTION_MANAGER_WRITE: 'CONNECTION_MANAGER.CONNECTION_MANAGER_WRITE'
  },
  MODULE_MANAGER: {
    MODULE_MANAGER_EXECUTE: 'MODULE_MANAGER.MODULE_MANAGER_EXECUTE',
    MODULE_MANAGER_READ: 'MODULE_MANAGER.MODULE_MANAGER_READ',
    MODULE_MANAGER_WRITE: 'MODULE_MANAGER.MODULE_MANAGER_WRITE'
  },
  SERVER_INFO: {
    SERVER_INFO_EXECUTE: 'SERVER_INFO.SERVER_INFO_EXECUTE',
    SERVER_INFO_READ: 'SERVER_INFO.SERVER_INFO_READ',
    SERVER_INFO_WRITE: 'SERVER_INFO.SERVER_INFO_WRITE'
  },
  EDIT_IP_TABLE: {
    EDIT_IP_TABLE_EXECUTE: 'EDIT_IP_TABLE.EDIT_IP_TABLE_EXECUTE',
    EDIT_IP_TABLE_READ: 'EDIT_IP_TABLE.EDIT_IP_TABLE_READ',
    EDIT_IP_TABLE_WRITE: 'EDIT_IP_TABLE.EDIT_IP_TABLE_WRITE'
  },
  GROUP_CHART: {
    GROUP_CHART_WRITE: 'GROUP_CHART.GROUP_CHART_WRITE',
    GROUP_CHART_EXECUTE: 'GROUP_CHART.GROUP_CHART_EXECUTE',
    GROUP_CHART_READ: 'GROUP_CHART.GROUP_CHART_READ'
  },
  ETL_JOB_LIB: {
    ETL_JOB_LIB_EXECUTE: 'ETL_JOB_LIB.ETL_JOB_LIB_EXECUTE',
    ETL_JOB_LIB_WRITE: 'ETL_JOB_LIB.ETL_JOB_LIB_WRITE',
    ETL_JOB_LIB_READ: 'ETL_JOB_LIB.ETL_JOB_LIB_READ',
  },
  DATA_LAKE: {
    DATALAKE_EXECUTE: 'DATA_LAKE.DATALAKE_EXECUTE',
    DATALAKE_WRITE: 'DATA_LAKE.DATALAKE_WRITE',
    DATALAKE_READ: 'DATA_LAKE.DATALAKE_READ',
  },
  DB_MAKE_FILE_CONFIG: {
    DB_MAKE_FILE_CONFIG_WRITE: 'DB_MAKE_FILE_CONFIG.DB_MAKE_FILE_CONFIG_WRITE',
    DB_MAKE_FILE_CONFIG_READ: 'DB_MAKE_FILE_CONFIG.DB_MAKE_FILE_CONFIG_READ',
    DB_MAKE_FILE_CONFIG_EXECUTE: 'DB_MAKE_FILE_CONFIG.DB_MAKE_FILE_CONFIG_EXECUTE',
  },
  ACCESS_MANAGEMENT: {
    ACCESS_MANAGEMENT_WRITE: 'ACCESS_MANAGEMENT.ACCESS_MANAGEMENT_WRITE',
    ACCESS_MANAGEMENT_READ: 'ACCESS_MANAGEMENT.ACCESS_MANAGEMENT_READ',
    ACCESS_MANAGEMENT_EXECUTE: 'ACCESS_MANAGEMENT.ACCESS_MANAGEMENT_EXECUTE',
  },
  ENCRYPT_TOOLS: {
    ENCRYPT_TOOLS_EXECUTE: 'ENCRYPT_TOOLS.ENCRYPT_TOOLS_EXECUTE',
    ENCRYPT_TOOLS_READ: 'ENCRYPT_TOOLS.ENCRYPT_TOOLS_READ',
    ENCRYPT_TOOLS_WRITE: 'ENCRYPT_TOOLS.ENCRYPT_TOOLS_WRITE',
  },
  DU_FILE_HDFS: {
    DU_FILE_HDFS_WRITE: 'DU_FILE_HDFS.DU_FILE_HDFS_WRITE',
    DU_FILE_HDFS_READ: 'DU_FILE_HDFS.DU_FILE_HDFS_READ',
    DU_FILE_HDFS_EXECUTE: 'DU_FILE_HDFS.DU_FILE_HDFS_EXECUTE',
  },
  ATLAS_UPDATE: {
    ATLAS_UPDATE_WRITE: 'ATLAS_UPDATE.ATLAS_UPDATE_WRITE',
    ATLAS_UPDATE_READ: 'ATLAS_UPDATE.ATLAS_UPDATE_READ',
    ATLAS_UPDATE_EXECUTE: 'ATLAS_UPDATE.ATLAS_UPDATE_EXECUTE',
  },
  ALERT_CONFIG: {
    ALERT_CONFIG_WRITE: 'ALERT_CONFIG.ALERT_CONFIG_WRITE',
    ALERT_CONFIG_READ: 'ALERT_CONFIG.ALERT_CONFIG_READ',
    ALERT_CONFIG_EXECUTE: 'ALERT_CONFIG.ALERT_CONFIG_EXECUTE',
  },
  DASHBOARD: {
    DASHBOARD_WRITE: 'DASHBOARD.DASHBOARD_WRITE',
    DASHBOARD_READ: 'DASHBOARD.DASHBOARD_READ',
    DASHBOARD_EXECUTE: 'DASHBOARD.DASHBOARD_EXECUTE',
  },
  SMS_ALERT_CONFIG: {
    SMS_ALERT_CONFIG_WRITE: 'SMS_ALERT_CONFIG.SMS_ALERT_CONFIG_WRITE',
    SMS_ALERT_CONFIG_READ: 'SMS_ALERT_CONFIG.SMS_ALERT_CONFIG_READ',
    SMS_ALERT_CONFIG_EXECUTE: 'SMS_ALERT_CONFIG.SMS_ALERT_CONFIG_EXECUTE',
  },
  DU_FILE_SERVER: {
    DU_FILE_SERVER_WRITE: 'DU_FILE_SERVER.DU_FILE_SERVER_WRITE',
    DU_FILE_SERVER_READ: 'DU_FILE_SERVER.DU_FILE_SERVER_READ',
    DU_FILE_SERVER_EXECUTE: 'DU_FILE_SERVER.DU_FILE_SERVER_EXECUTE',
  },
  LB_CONNECTION: {
    LB_CONNECTION_WRITE: 'LB_CONNECTION.LB_CONNECTION_WRITE',
    LB_CONNECTION_READ: 'LB_CONNECTION.LB_CONNECTION_READ',
    LB_CONNECTION_EXECUTE: 'LB_CONNECTION.LB_CONNECTION_EXECUTE',
  },
  THRIFT_ACCESS_RULE: {
    THRIFT_ACCESS_RULE_WRITE: 'THRIFT_ACCESS_RULE.THRIFT_ACCESS_RULE_WRITE',
    THRIFT_ACCESS_RULE_READ: 'THRIFT_ACCESS_RULE.THRIFT_ACCESS_RULE_READ',
    THRIFT_ACCESS_RULE_EXECUTE: 'THRIFT_ACCESS_RULE.THRIFT_ACCESS_RULE_EXECUTE',
  },
  THRIFT_INFO: {
    THRIFT_INFO_WRITE: 'THRIFT_INFO.THRIFT_INFO_WRITE',
    THRIFT_INFO_READ: 'THRIFT_INFO.THRIFT_INFO_READ',
    THRIFT_INFO_EXECUTE: 'THRIFT_INFO.THRIFT_INFO_EXECUTE',
  },
  ACCESS_LOG: {
    ACCESS_LOG_WRITE: 'ACCESS_LOG.ACCESS_LOG_WRITE',
    ACCESS_LOG_READ: 'ACCESS_LOG.ACCESS_LOG_READ',
    ACCESS_LOG_EXECUTE: 'ACCESS_LOG.ACCESS_LOG_EXECUTE',
  },
  DB_ORACLE_MANAGER: {
    DB_ORACLE_MANAGER_WRITE: 'DB_ORACLE_MANAGER.DB_ORACLE_MANAGER_WRITE',
    DB_ORACLE_MANAGER_READ: 'DB_ORACLE_MANAGER.DB_ORACLE_MANAGER_READ',
    DB_ORACLE_MANAGER_EXECUTE: 'DB_ORACLE_MANAGER.DB_ORACLE_MANAGER_EXECUTE',
  },
  TABLE_LOOKUP: {
    TABLE_LOOKUP_WRITE: 'TABLE_LOOKUP.TABLE_LOOKUP_WRITE',
    TABLE_LOOKUP_READ: 'TABLE_LOOKUP.TABLE_LOOKUP_READ',
    TABLE_LOOKUP_EXECUTE: 'TABLE_LOOKUP.TABLE_LOOKUP_EXECUTE',
  },
  IP_TABLE_RULE: {
    IP_TABLE_RULE_WRITE: 'IP_TABLE_RULE.IP_TABLE_RULE_WRITE',
    IP_TABLE_RULE_READ: 'IP_TABLE_RULE.IP_TABLE_RULE_READ',
    IP_TABLE_RULE_EXECUTE: 'IP_TABLE_RULE.IP_TABLE_RULE_EXECUTE',
  },
  FLOW_CUSTOMIZED: {
    FLOW_CUSTOMIZED_WRITE: 'FLOW_CUSTOMIZED.FLOW_CUSTOMIZED_WRITE',
    FLOW_CUSTOMIZED_READ: 'FLOW_CUSTOMIZED.FLOW_CUSTOMIZED_READ',
    FLOW_CUSTOMIZED_EXECUTE: 'FLOW_CUSTOMIZED.FLOW_CUSTOMIZED_EXECUTE',
  },
  RP_APP: {
    RP_APP_EXECUTE: 'RP_APP.RP_APP_EXECUTE',
    RP_APP_READ: 'RP_APP.RP_APP_READ',
    RP_APP_WRITE: 'RP_APP.RP_APP_WRITE',
  },
  SUPPORT_REQUEST: {
    SUPPORT_REQUEST_EXECUTE: 'SUPPORT_REQUEST.SUPPORT_REQUEST_EXECUTE',
    SUPPORT_REQUEST_READ: 'SUPPORT_REQUEST.SUPPORT_REQUEST_READ',
    SUPPORT_REQUEST_WRITE: 'SUPPORT_REQUEST.SUPPORT_REQUEST_WRITE',
  }
};
